_core:
  default_config_hash: qgvkQXIbpBNBsbs1QpPWaiBwLuQggFrGaTq6n2i6RlA
langcode: en-gb
field_widget_prompt: "You will be asked to help with content suggestions based on the input in markdown format. Answer with\r\nsuggestions only, do not repeat the task description, do not use any other text except for the suggestions.\r\nDo not include any explanations, only provide a RFC8259 compliant JSON response following this format without deviation:\r\n```\r\n[\r\n  {\"suggestion\": \"First suggested text\"},\r\n  {\"suggestion\": \"Second suggested text\"},\r\n]\r\n```\r\nIf you are enable to generate a response, respond with \"Insufficient information provided, please add more data before generating suggestions.\"\r\n"
plugins:
  readability: openai__gpt-4o
  taxonomy_suggest: openai__gpt-4o
enabled_content_types:
  article: article
mode: enable
