name: 'Configuration Manager'
type: module
description: 'Allows importing and exporting configuration changes.'
package: Core
version: VERSION
container_rebuild_required: false
configure: config.sync
